[project]
site_name = "RH Community Plugins"
site_url = "https://rotorhazard.github.io/community-plugins/"
site_author = "Klaas Schoute"
site_description = "A database of community-driven plugin for RotorHazard."
copyright = """
&copy; 2026 <a href="https://rotorhazard.com" target="_blank" rel="noopener">RotorHazard</a>
"""
repo_name = "community-plugins"
repo_url = "https://github.com/rotorhazard/community-plugins"
docs_dir = "docs"
site_dir = "site"
nav = [
  { "Home" = "index.md" },
  { "Plugins Database" = "database.md" },
  { "Publish a Plugin" = [
    { "Getting started" = "docs/plugin/index.md" },
    { "Include repository" = "docs/plugin/include.md" },
    { "Remove repository" = "docs/plugin/remove.md" },
    { "Build your first plugin" = "docs/plugin/tutorial.md" },
  ] },
  { "RHFest Action" = [
    "docs/rhfest/index.md",
  ] },
  { "FAQ" = [
    "faq/index.md",
    "faq/general.md",
    "faq/development.md",
    "faq/publishing.md",
    "faq/troubleshooting.md",
    "faq/categories.md",
    "faq/licensing.md",
  ] },
  { "Help" = [
    "help/index.md",
  ] },
]
extra_javascript = ["assets/js/dataLoader.js"]
extra_css = ["assets/css/faq.css"]

[project.theme]
variant = "classic"
language = "en"
custom_dir = "docs/overrides"
logo = "assets/img/logo_light.svg"
favicon = "assets/img/favicon.ico"
features = [
  "content.code.annotate",
  "content.code.copy",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.instant.progress",
  "navigation.path",
  "navigation.tabs",
  "navigation.tabs.sticky",
  "navigation.top",
  "navigation.tracking",
  "navigation.footer",
  "search.highlight",
]

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "orange"
toggle.icon = "lucide/moon"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "black"
toggle.icon = "lucide/sun"
toggle.name = "Switch to light mode"

[project.markdown_extensions.attr_list]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.pymdownx.arithmatex]
generic = true

[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.mark]

[project.markdown_extensions.toc]
permalink = true

[project.extra]
manifest = "assets/manifest.json"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/RotorHazard"

[[project.extra.social]]
icon = "fontawesome/brands/discord"
link = "https://discord.gg/ANKd2pzBKH"

[[project.extra.social]]
icon = "fontawesome/brands/youtube"
link = "https://www.youtube.com/@RotorHazard"

[[project.extra.social]]
icon = "fontawesome/brands/facebook"
link = "https://www.facebook.com/groups/rotorhazard"
